Repository JanJorgensen/StepBro, pull requests merged in 2023-06, with the labels that each got.

#33 Folder Shortcuts
  source/StepBro.Core/Api/Constants.cs
  source/StepBro.Core/Data/UICallContext.cs
  source/StepBro.Core/Execution/CallContext.cs
  source/StepBro.Core/Execution/FunctionCallContextWrapper.cs
  source/StepBro.Core/Execution/ScriptCallContext.cs
  source/StepBro.Core/File/FileReference.cs
  source/StepBro.Core/Interface/Main.cs
  source/StepBro.Core/ScriptData/IScriptFile.cs
  source/StepBro.Core/ScriptData/ScriptFile.cs
  source/Test/StepBro.Core.Test/ConceptualFileImplementation.cs
  source/stepbro/Program.cs
Labels: enhancement

#38 To show that we are still in development and so we can actually incre…
  source/CommonVersion.cs
  source/StepBroSetup.iss
  source/Test/StepBro.Core.Test/Parser/Expression/TestMethodCall.cs
  source/Test/StepBro.Core.Test/Parser/TestFileParsing.cs
  source/stepbro/StepBro.Console.csproj
Labels: documentation

#42 40 improve parsing error on unknown identifier
  source/StepBro.Core/Parser/StepBroListener.Expression.cs
  source/Test/StepBro.Core.Test/Parser/TestFileParsingErrors.cs
Labels: bug, enhancement

#51 Change variable definition syntax
  source/StepBro.Core/Api/ObjectNameAttribute.cs
  source/StepBro.Core/Parser/StepBro.g4
  source/StepBro.Core/Parser/StepBroListener.Variable.cs
  source/StepBro.Core/Parser/StepBroListener.cs
  source/Test/StepBro.Core.Test/Execution/FormalTestSetupExecution.cs
  source/Test/StepBro.Core.Test/Execution/TestLayeredModuleUsage.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_IfElse.cs
  source/Test/StepBro.Core.Test/Parser/TestFileParsing.cs
  source/Test/StepBro.Core.Test/Parser/TestFileVariables.cs
Labels: enhancement
