Repository JanJorgensen/StepBro, pull requests merged in 2023-09, with the labels that each got.

#87 74 for loop is not implemented
  source/CommonVersion.cs
  source/StepBro.Core/Parser/ProcedureParsingScope.cs
  source/StepBro.Core/Parser/StepBro.g4
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
  source/StepBroSetup.iss
  source/Test/StepBro.Core.Test/Execution/TestProcedure_For.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_While.cs
  source/stepbro/StepBro.Console.csproj
Labels: enhancement

#90 88 continue does not work in loops
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_For.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_While.cs
Labels: bug, enhancement

#91 89 Loop statement disappears if it is only statement inside another loop (without {})
  source/StepBro.Core/Parser/StepBro.g4
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_For.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_While.cs
Labels: bug, enhancement

#92 76 Re-defining a variable does not give a warning or error
  source/StepBro.Core/Parser/StepBroListener.Variable.cs
  source/Test/StepBro.Core.Test/Parser/Procedure/TestLocalVariables.cs
Labels: bug

#93 75 asynclogcurrenttimestampmillisecond does not seem to give an answer if we have just awaited the last log message
  source/StepBro.Core/Data/ILineReader.cs
  source/StepBro.Core/Data/LineReaders.cs
  source/StepBro.Core/Data/LogLineLineReader.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
Labels: enhancement

#98 Azure logging fix
  scripts/TestFramework.sbs
  source/StepBro.Core/Addons/OutputAzurePipelineFormatAddon.cs
  source/StepBro.Core/Data/Report/DataReport.cs
  source/StepBro.Core/Parser/FileBuilder.cs
  source/StepBro.Core/Parser/StepBro.g4
  source/StepBro.Core/Parser/StepBroListener.cs
  source/StepBro.Core/ScriptData/FileElement.cs
  source/StepBro.Core/ScriptData/IFileElement.cs
  test files/TestProject.sbs
Labels: enhancement

#103 Update execution status functionality
  source/StepBro.Core/Execution/CallContext.cs
  source/StepBro.Core/Execution/ExecutionScopeStatusUpdater.cs
  source/StepBro.Core/Execution/ExecutionStatusRoot.cs
  source/StepBro.Core/Execution/ExecutionStatusStack.cs
  source/StepBro.Core/Execution/FunctionCallContextWrapper.cs
  source/StepBro.Core/Execution/IExecutionScopeStatusUpdate.cs
  source/StepBro.Core/Execution/IProcedureThis.cs
  source/StepBro.Core/Execution/IScriptCallContext.cs
  source/StepBro.Core/Execution/IScriptExecution.cs
  source/StepBro.Core/Execution/IScriptExecutionManager.cs
  source/StepBro.Core/Execution/ScriptCallContext.cs
  source/StepBro.Core/Execution/ScriptExecutionManager.cs
  source/StepBro.Core/Execution/ScriptExecutionTask.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
  source/StepBro.Core/Interface/Main.cs
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
  source/Test/StepBro.Core.Test/Mocks/ExecutionScopeStatusUpdaterMock.cs
  test files/StepBro Selftest.sbs
Labels: bug, enhancement

#102 95 Occasionally asynclog is unable to locate a matching entry, even when there is a matching entry
  source/Modules/StepBro.Streams/SerialPort.cs
  source/Modules/StepBro.TestInterface/SerialTestConnection.cs
  source/StepBro.Core/Data/ILineReader.cs
  source/StepBro.Core/Data/LineReaders.cs
  source/StepBro.Core/Data/LogLineLineReader.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
  source/Test/StepBro.Core.Test/Execution/TestPublicCoreMethods.cs
Labels: bug

#105 Add unit tests for LogLineLineReader and fix a few issues
  source/StepBro.Core/Data/LogLineData.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
  source/Test/StepBro.Core.Test/Data/DummyClass.cs
  source/Test/StepBro.Core.Test/Data/TestLineReader.cs
Labels: bug, enhancement

#106 Fix #37
  source/Modules/StepBro.TestInterface/SerialTestConnection.cs
Labels: bug
