Repository JanJorgensen/StepBro, pull requests merged in 2024-06, with the labels that each got.

#260 255 make timeout accurate in instrumentusingbridgecs
  source/Modules/StepBro.VISA/InstrumentUsingBridge.cs
  source/StepBro.VISABridge/MainForm.cs
  source/StepBro.VISABridge/StepBroVISAMessages.cs
Labels: bug

#261 Fix #167
  source/StepBro.Core/Parser/SBExpressionData.cs
  source/Test/StepBro.Core.Test/Parser/TestProcedureParsing.cs
Labels: bug

#265 Change timestamps from DateTime.Now to DateTime.UtcNow
  source/StepBro.Core/Data/LogLineData.cs
  source/StepBro.Core/Data/Report/DataReport.cs
  source/StepBro.Core/Data/Report/ExpectResultData.cs
  source/StepBro.Core/Data/Report/TableData.cs
  source/StepBro.Core/Data/TimeUtils.cs
  source/StepBro.Core/Data/TimedDataQueue.cs
  source/StepBro.Core/Execution/ExecutionScopeStatusUpdater.cs
  source/StepBro.Core/Execution/ICallContext.cs
  source/StepBro.Core/Execution/ScriptCallContext.cs
  source/StepBro.Core/Execution/ScriptExecutionTask.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
  source/StepBro.Core/General/HostApplicationActionQueue.cs
  source/StepBro.Core/Logging/DebugLogEntry.cs
  source/StepBro.Core/Logging/LogFileCreationManager.cs
  source/StepBro.Core/Logging/Logger.cs
  source/StepBro.Core/Logging/LoggerScope.cs
  source/StepBro.Core/Parser/FileBuilder.cs
  source/StepBro.Core/ScriptData/ScriptFile.cs
  source/stepbro/Program.cs
Labels: enhancement

#268 Fix type tuple
  source/StepBro.Core/Parser/StepBroListener.Identifier.cs
  source/StepBro.Core/Parser/StepBroListener.Type.cs
  source/StepBro.Core/ScriptData/ScriptFile.cs
  source/Test/StepBro.Core.Test/Parser/TestFileParsing.cs
Labels: bug

#270 267 fix type so it works instead of using properly
  source/StepBro.Core/Parser/StepBroListener.ExpressionMethodCall.cs
  source/Test/StepBro.Core.Test/Parser/TestFileParsing.cs
Labels: bug

#272 271 if a type is exposed to a script through several usings an exception is thrown
  source/StepBro.Core/Parser/StepBroListener.Identifier.cs
Labels: bug

#274 Cleaner solution for multiple of same type
  source/StepBro.Core/Parser/StepBroListener.Identifier.cs
  source/StepBro.Core/ScriptData/ScriptFile.cs
Labels: enhancement

#273 Make it possible to send mail through StepBro scripts
  source/StepBro.Core/Execution/ScriptUtils.cs
  source/StepBro.Core/Utils/MailSender.cs
Labels: enhancement

#276 275 global variables can not be assigned besides their initial value
  source/StepBro.Core/Execution/ExecutionHelperMethods.cs
  source/StepBro.Core/Parser/AssignmentOperators/AssignmentOperator.cs
  source/StepBro.Core/Parser/BinaryOperators/DivideOperator.cs
  source/StepBro.Core/Parser/StepBroListener.Expression.cs
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
Labels: bug

#277 Make a variable long
  source/Modules/StepBro.ExecutionHelper.Access/Access.cs
Labels: bug

#282 Inner exception has slightly better information
  source/StepBro.Core/Execution/ExecutionHelperMethods.cs
Labels: bug

#284 Add null and out to syntax highlighting. Update version number. Creat…
  additional/stepbro-syntax-highlighting/package.json
  additional/stepbro-syntax-highlighting/stepbro-syntax-highlighting-0.0.3.vsix
  additional/stepbro-syntax-highlighting/syntaxes/stepbro.tmLanguage.json
Labels: enhancement

#285 279 improve executionhelper
  source/CommonVersion.cs
  source/Modules/StepBro.ExecutionHelper.Access/Access.cs
  source/StepBro.Core/Interface/Main.cs
  source/StepBro.ExecutionHelper/ExecutionHelperMessages.cs
  source/StepBro.ExecutionHelper/MainForm.cs
  source/StepBroSetup.iss
  source/stepbro/StepBro.Console.csproj
Labels: enhancement

#286 Fix issue where path would not include \\ in savefile backups
  source/StepBro.ExecutionHelper/MainForm.cs
Labels: bug

#290 289 document executionhelper and visa
  source/Modules/StepBro.ExecutionHelper.Access/Access.cs
  source/Modules/StepBro.VISA/InstrumentUsingBridge.cs
  source/StepBro.Core/Parser/StepBroListener.ExpressionMethodCall.cs
  source/StepBro.Core/Parser/StepBroListener.Variable.cs
Labels: bug, documentation

#296 292 make executionhelper check for certain updates during periodic checks
  source/StepBro.ExecutionHelper/MainForm.cs
Labels: enhancement

#298 280 make it possible to save report to a specific file
  source/StepBro.Core/Addons/IOutputFormatter.cs
  source/StepBro.Core/Addons/OutputAzurePipelineFormatAddon.cs
  source/StepBro.Core/Addons/OutputConsoleWithColorsAddon.cs
  source/StepBro.Core/Addons/OutputHtmlAddon.cs
  source/StepBro.Core/Addons/OutputSimpleCleartextAddon.cs
  source/stepbro/CommandLineOptions.cs
  source/stepbro/Program.cs
Labels: enhancement

#300 299 verbose does not write anything out after last commit
  source/StepBro.Core/Addons/OutputAzurePipelineFormatAddon.cs
  source/StepBro.Core/Addons/OutputConsoleWithColorsAddon.cs
  source/stepbro/Program.cs
Labels: bug

#301 297 in test summary left and right show 0 if they are not shown in the expect
  source/StepBro.Core/Parser/StepBroListener.Expression.cs
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
Labels: bug, enhancement

#303 fix #295
  source/StepBro.Core/Parser/StepBroListener.Expression.cs
Labels: bug
