Repository JanJorgensen/StepBro, pull requests merged in 2024-04, with the labels that each got.

#178 172
  source/StepBro.Core/ScriptData/FileElement.cs
Labels: bug

#184 Fix a race condition
  source/StepBro.Core/Data/LogLineLineReader.cs
  source/StepBro.Core/Execution/ScriptUtils.cs
Labels: bug

#185 180 write out value of all variables in an expect so it is easier to debug when a test fails
  source/StepBro.Core/Execution/ExecutionHelperMethods.cs
  source/StepBro.Core/Execution/ScriptCallContext.cs
  source/StepBro.Core/Parser/StepBroListener.Expression.cs
  source/Test/StepBro.Core.Test/Execution/FormalTestSetupExecution.cs
  source/Test/StepBro.Core.Test/Execution/TestProcedure_ErrorHandling.cs
  source/Test/StepBro.Core.Test/Execution/TestPublicCoreMethods.cs
Labels: enhancement

#198 196 connect stepbrovisa with stepbrovisabridge
  source/Modules/StepBro.ExecutionHelper.Access/Access.cs
  source/Modules/StepBro.VISA/InstrumentUsingBridge.cs
  source/Modules/StepBro.VISA/StepBro.VISA.csproj
  source/StepBro.Core/IPC/Pipe.cs
  source/StepBro.ExecutionHelper/ExecutionHelperMessages.cs
  source/StepBro.ExecutionHelper/MainForm.cs
  source/StepBro.VISABridge/App.config
  source/StepBro.VISABridge/MainForm.cs
  source/StepBro.VISABridge/StepBro.VISABridge.csproj
  source/StepBro.VISABridge/StepBroVISAMessages.cs
  source/StepBro.VISABridge/packages.config
  test files/ModuleTests/ExecutionHelper/ExecutionHelperTests.sbs
  test files/ModuleTests/VISA/VISATests.sbs
Labels: enhancement

#197 Update dotnet-desktop.yml
  .github/workflows/dotnet-desktop.yml
Labels: enhancement

#211 Fix assigning Int32 method return value to an 'int' (Int64) variable.
  source/StepBro.ConsoleSidekick.WinForms/MainForm.Designer.cs
  source/StepBro.Core/Execution/ScriptTaskContext.cs
  source/StepBro.Core/Parser/StepBroListener.ExpressionMethodCall.cs
  source/Test/StepBro.Core.Test/Data/DummyClass.cs
  source/Test/StepBro.Core.Test/Parser/Expression/TestMethodCall.cs
Labels: bug

#209 208 dispose pipe automatically when closing executionhelper or visa
  .gitignore
  source/Modules/StepBro.ExecutionHelper.Access/Access.cs
  source/Modules/StepBro.Streams/SerialPort.cs
  source/Modules/StepBro.TestInterface/SerialTestConnection.cs
  source/Modules/StepBro.VISA/InstrumentUsingBridge.cs
  source/StepBro.ConsoleSidekick.WinForms/MainForm.cs
  source/StepBro.Core/Data/DynamicObjectManager.cs
  source/StepBro.Core/Data/VariableContainer.cs
  source/StepBro.Core/IPC/Pipe.cs
  source/StepBro.Core/ScriptData/ScriptFile.cs
  source/StepBro.ExecutionHelper/MainForm.cs
  source/StepBro.VISABridge/MainForm.cs
  source/stepbro/Program.cs
  test files/ModuleTests/VISA/VISATests.sbs
Labels: bug, enhancement

#220 199 no parsing error on unknown or misspelled property on while or for loop
  source/StepBro.Core/Parser/StepBroListener.Procedure.cs
Labels: bug

#221 217-objectdisposedexception-in-sidekick-pipe-when-stepbroexe-closes
  source/StepBro.Core/IPC/Pipe.cs
Labels: bug
